name: test-auth
on:
  pull_request:
    paths:
     - 'auth/**'
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.15.1'
      - name: Install Yarn
        run: npm install --location=global yarn
      - name: Run test 
        run: cd auth && yarn && yarn test:ci
